---
services:
  vcv:
    image: jhmmt/vcv:1.3
    container_name: vcv
    restart: unless-stopped
    ports:
      - "52000:52000/tcp"
    cap_drop:
      - ALL
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./settings.json:/app/settings.json:ro
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 64M
